%dev.quarkus.rest-client.product-service-client.url=http://localhost:8080
%k8s.quarkus.kubernetes.idempotent=true
%k8s.quarkus.kubernetes.output-directory=kubernetes
%k8s.quarkus.kubernetes.namespace=default
%k8s.quarkus.kubernetes.env.vars.quarkus-application-version=${quarkus.application.version}
%k8s.quarkus.kubernetes.env.vars."quarkus.rest-client.product-service-client.url"=http://istio-lab.cch.com:9080
%k8s.quarkus.kubernetes.hostaliases."192.168.153.132".hostnames=istio-lab.cch.com
%k8s.quarkus.kubernetes.env.fields."POD_NAME"=metadata.name
%k8s.quarkus.kubernetes.resources.requests.memory=64Mi
%k8s.quarkus.kubernetes.resources.requests.cpu=250m
%k8s.quarkus.kubernetes.resources.limits.memory=512Mi
%k8s.quarkus.kubernetes.resources.limits.cpu=1000m
%k8s.quarkus.kubernetes.labels."version"=${quarkus.application.version}
%k8s.quarkus.kubernetes.labels."sidecar.istio.io/inject"=true
%k8s.quarkus.kubernetes.enabled=true
quarkus.container-image.group=cch0124
quarkus.container-image.name=${quarkus.application.name:unset}
quarkus.container-image.tag=${quarkus.application.version:latest}
quarkus.container-image.builder=jib
quarkus.container-image.labels."maintainer"=cch
quarkus.container-image."app"=${quarkus.application.name}
quarkus.container-image.registry=registry.hub.docker.com
quarkus.jib.platforms=linux/amd64
quarkus.application.version=v0.0.1