quarkus.rest-client.product-service-client.url=http://localhost:9000
quarkus.kubernetes.idempotent=true
quarkus.kubernetes.output-directory=kubernetes
quarkus.kubernetes.namespace=default
quarkus.kubernetes.resources.requests.memory=64Mi
quarkus.kubernetes.resources.requests.cpu=250m
quarkus.kubernetes.resources.limits.memory=512Mi
quarkus.kubernetes.resources.limits.cpu=1000m
quarkus.kubernetes.labels."version" = v1
quarkus.kubernetes.annotations."sidecar.istio.io/inject"=true
quarkus.container-image.group: cch0124
quarkus.container-image.name: ${quarkus.application.name:unset}
quarkus.container-image.tag: ${quarkus.application.version:latest}
quarkus.container-image.builder: jib
quarkus.container-image.labels."maintainer": cch
quarkus.container-image."app": ${quarkus.application.name}
quarkus.container-image.registry: registry.hub.docker.com
quarkus.jib.platforms: linux/amd64